
services:
  postgres:
    image: postgres
    container_name: postgres_tapsecure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: tapsecure_dev
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
